name: Main Deploy Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: main_deploy
  cancel-in-progress: true

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare web
        run: ./prepare.sh
      - uses: actions/setup-node@v6
      - run: npm install tailwindcss @tailwindcss/cli
      - run: npx tailwindcss -i ./src/styles.css -o ./src/assets/tailwind.css --minify
      - run: npx @11ty/eleventy
      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: fluffy.chat
